alter table auth_user modify email varchar(255);


INSERT INTO apparel_optiontype VALUES(1,'Size','Size Parent Node',NULL,1,10,3,0);
INSERT INTO apparel_optiontype VALUES(2,'Shoe Size (EU)','European sizes (numeric)',1,8,9,3,1);
INSERT INTO apparel_optiontype VALUES(3,'Pants (Length)','Length of pants or trousers',1,2,3,3,1);
INSERT INTO apparel_optiontype VALUES(4,'Pants (Width)','Width of pants or trousers',1,4,5,3,1);
INSERT INTO apparel_optiontype VALUES(5,'Relative Size','Relative size (X*L, L, M, S, X*S)',1,6,7,3,1);
INSERT INTO apparel_optiontype VALUES(6,'Gender','Gender (M, F or U)',NULL,1,2,2,0);
INSERT INTO apparel_optiontype VALUES(7,'Color','Color as plain text (in English)',NULL,1,2,1,0);


INSERT INTO apparel_category VALUES(1,'jewelry','Jewelry',NULL,0,1,2,13,0);
INSERT INTO apparel_category VALUES(2,'chinos','Chinos',NULL,0,1,2,6,0);
INSERT INTO apparel_category VALUES(3,'jeans','Jeans',NULL,0,1,2,12,0);
INSERT INTO apparel_category VALUES(4,'watches','Watches',NULL,0,1,2,30,0);
INSERT INTO apparel_category VALUES(5,'sunglasses','Sunglasses',NULL,0,1,2,24,0);
INSERT INTO apparel_category VALUES(6,'vest','Vest',NULL,0,1,2,29,0);
INSERT INTO apparel_category VALUES(7,'caps','Caps',NULL,0,1,2,4,0);
INSERT INTO apparel_category VALUES(8,'gloves','Gloves',NULL,0,1,2,9,0);
INSERT INTO apparel_category VALUES(9,'hats','Hats',NULL,0,1,2,10,0);
INSERT INTO apparel_category VALUES(10,'coats','Coats',NULL,0,1,2,7,0);
INSERT INTO apparel_category VALUES(11,'boots','Boots',NULL,0,1,2,2,0);
INSERT INTO apparel_category VALUES(12,'ties','Ties',NULL,0,1,2,27,0);
INSERT INTO apparel_category VALUES(13,'long-sleeve','Long Sleeve',NULL,0,1,2,15,0);
INSERT INTO apparel_category VALUES(14,'bow-tie','Bow tie',NULL,0,1,2,3,0);
INSERT INTO apparel_category VALUES(15,'sneakers','Sneakers',NULL,0,1,2,21,0);
INSERT INTO apparel_category VALUES(16,'polo-shirt','Polo shirt',NULL,0,1,2,17,0);
INSERT INTO apparel_category VALUES(17,'t-shirts','T-shirts',NULL,0,1,2,26,0);
INSERT INTO apparel_category VALUES(18,'farsfars','Farsfars',NULL,0,1,2,8,0);
INSERT INTO apparel_category VALUES(19,'trunks','Trunks',NULL,0,1,2,28,0);
INSERT INTO apparel_category VALUES(20,'lap-top-skins','Lap top skins',NULL,0,1,2,14,0);
INSERT INTO apparel_category VALUES(21,'bags','Bags',NULL,0,1,2,1,0);
INSERT INTO apparel_category VALUES(22,'summer-jackets','Summer Jackets',NULL,0,1,2,23,0);
INSERT INTO apparel_category VALUES(23,'parkas','Parkas',NULL,0,1,2,16,0);
INSERT INTO apparel_category VALUES(24,'cardigan','Cardigan',NULL,0,1,2,5,0);
INSERT INTO apparel_category VALUES(25,'sweatshirt','Sweatshirt',NULL,0,1,2,25,0);
INSERT INTO apparel_category VALUES(26,'socks','Socks',NULL,0,1,2,22,0);
INSERT INTO apparel_category VALUES(27,'zip-shirt','Zip shirt',NULL,0,1,2,31,0);
INSERT INTO apparel_category VALUES(28,'scarfs','Scarfs',NULL,0,1,2,20,0);
INSERT INTO apparel_category VALUES(29,'racing','Racing',NULL,0,1,2,19,0);
INSERT INTO apparel_category VALUES(30,'hoodie','Hoodie',NULL,0,1,2,11,0);
INSERT INTO apparel_category VALUES(31,'pullover','Pullover',NULL,0,1,2,18,0);


INSERT INTO apparel_category_option_types VALUES(1,21,6);
INSERT INTO apparel_category_option_types VALUES(2,21,7);
INSERT INTO apparel_category_option_types VALUES(3,11,6);
INSERT INTO apparel_category_option_types VALUES(4,11,2);
INSERT INTO apparel_category_option_types VALUES(5,11,7);
INSERT INTO apparel_category_option_types VALUES(6,14,7);
INSERT INTO apparel_category_option_types VALUES(7,7,7);
INSERT INTO apparel_category_option_types VALUES(8,24,6);
INSERT INTO apparel_category_option_types VALUES(9,24,7);
INSERT INTO apparel_category_option_types VALUES(10,24,5);
INSERT INTO apparel_category_option_types VALUES(14,10,6);
INSERT INTO apparel_category_option_types VALUES(15,10,7);
INSERT INTO apparel_category_option_types VALUES(16,10,5);
INSERT INTO apparel_category_option_types VALUES(17,8,7);
INSERT INTO apparel_category_option_types VALUES(18,9,7);
INSERT INTO apparel_category_option_types VALUES(19,30,6);
INSERT INTO apparel_category_option_types VALUES(20,30,7);
INSERT INTO apparel_category_option_types VALUES(21,30,5);
INSERT INTO apparel_category_option_types VALUES(22,3,6);
INSERT INTO apparel_category_option_types VALUES(23,3,3);
INSERT INTO apparel_category_option_types VALUES(24,3,4);
INSERT INTO apparel_category_option_types VALUES(25,3,7);
INSERT INTO apparel_category_option_types VALUES(26,2,6);
INSERT INTO apparel_category_option_types VALUES(27,2,3);
INSERT INTO apparel_category_option_types VALUES(28,2,4);
INSERT INTO apparel_category_option_types VALUES(29,2,7);
INSERT INTO apparel_category_option_types VALUES(30,13,6);
INSERT INTO apparel_category_option_types VALUES(31,13,7);
INSERT INTO apparel_category_option_types VALUES(32,13,5);
INSERT INTO apparel_category_option_types VALUES(33,23,6);
INSERT INTO apparel_category_option_types VALUES(34,23,7);
INSERT INTO apparel_category_option_types VALUES(35,23,5);
INSERT INTO apparel_category_option_types VALUES(36,16,6);
INSERT INTO apparel_category_option_types VALUES(37,16,7);
INSERT INTO apparel_category_option_types VALUES(38,16,5);
INSERT INTO apparel_category_option_types VALUES(39,28,7);
INSERT INTO apparel_category_option_types VALUES(40,15,6);
INSERT INTO apparel_category_option_types VALUES(41,15,2);
INSERT INTO apparel_category_option_types VALUES(42,15,7);
INSERT INTO apparel_category_option_types VALUES(43,26,6);
INSERT INTO apparel_category_option_types VALUES(44,26,7);
INSERT INTO apparel_category_option_types VALUES(45,22,6);
INSERT INTO apparel_category_option_types VALUES(46,22,7);
INSERT INTO apparel_category_option_types VALUES(47,22,5);
INSERT INTO apparel_category_option_types VALUES(48,25,6);
INSERT INTO apparel_category_option_types VALUES(49,25,7);
INSERT INTO apparel_category_option_types VALUES(50,25,5);
INSERT INTO apparel_category_option_types VALUES(51,17,6);
INSERT INTO apparel_category_option_types VALUES(52,17,7);
INSERT INTO apparel_category_option_types VALUES(53,17,5);
INSERT INTO apparel_category_option_types VALUES(54,6,6);
INSERT INTO apparel_category_option_types VALUES(55,6,7);
INSERT INTO apparel_category_option_types VALUES(56,6,5);
INSERT INTO apparel_category_option_types VALUES(57,4,6);
INSERT INTO apparel_category_option_types VALUES(58,27,6);
INSERT INTO apparel_category_option_types VALUES(59,27,7);
INSERT INTO apparel_category_option_types VALUES(60,27,5);


