BEGIN TRANSACTION;
INSERT INTO "apparel_category" VALUES(1,'jewelry','Jewelry',NULL,0,1,2,13,0);
INSERT INTO "apparel_category" VALUES(2,'chinos','Chinos',NULL,0,1,2,6,0);
INSERT INTO "apparel_category" VALUES(3,'jeans','Jeans',NULL,0,1,2,12,0);
INSERT INTO "apparel_category" VALUES(4,'watches','Watches',NULL,0,1,2,30,0);
INSERT INTO "apparel_category" VALUES(5,'sunglasses','Sunglasses',NULL,0,1,2,24,0);
INSERT INTO "apparel_category" VALUES(6,'vest','Vest',NULL,0,1,2,29,0);
INSERT INTO "apparel_category" VALUES(7,'caps','Caps',NULL,0,1,2,4,0);
INSERT INTO "apparel_category" VALUES(8,'gloves','Gloves',NULL,0,1,2,9,0);
INSERT INTO "apparel_category" VALUES(9,'hats','Hats',NULL,0,1,2,10,0);
INSERT INTO "apparel_category" VALUES(10,'coats','Coats',NULL,0,1,2,7,0);
INSERT INTO "apparel_category" VALUES(11,'boots','Boots',NULL,0,1,2,2,0);
INSERT INTO "apparel_category" VALUES(12,'ties','Ties',NULL,0,1,2,27,0);
INSERT INTO "apparel_category" VALUES(13,'long-sleeve','Long Sleeve',NULL,0,1,2,15,0);
INSERT INTO "apparel_category" VALUES(14,'bow-tie','Bow tie',NULL,0,1,2,3,0);
INSERT INTO "apparel_category" VALUES(15,'sneakers','Sneakers',NULL,0,1,2,21,0);
INSERT INTO "apparel_category" VALUES(16,'polo-shirt','Polo shirt',NULL,0,1,2,17,0);
INSERT INTO "apparel_category" VALUES(17,'t-shirts','T-shirts',NULL,0,1,2,26,0);
INSERT INTO "apparel_category" VALUES(18,'farsfars','Farsfars',NULL,0,1,2,8,0);
INSERT INTO "apparel_category" VALUES(19,'trunks','Trunks',NULL,0,1,2,28,0);
INSERT INTO "apparel_category" VALUES(20,'lap-top-skins','Lap top skins',NULL,0,1,2,14,0);
INSERT INTO "apparel_category" VALUES(21,'bags','Bags',NULL,0,1,2,1,0);
INSERT INTO "apparel_category" VALUES(22,'summer-jackets','Summer Jackets',NULL,0,1,2,23,0);
INSERT INTO "apparel_category" VALUES(23,'parkas','Parkas',NULL,0,1,2,16,0);
INSERT INTO "apparel_category" VALUES(24,'cardigan','Cardigan',NULL,0,1,2,5,0);
INSERT INTO "apparel_category" VALUES(25,'sweatshirt','Sweatshirt',NULL,0,1,2,25,0);
INSERT INTO "apparel_category" VALUES(26,'socks','Socks',NULL,0,1,2,22,0);
INSERT INTO "apparel_category" VALUES(27,'zip-shirt','Zip shirt',NULL,0,1,2,31,0);
INSERT INTO "apparel_category" VALUES(28,'scarfs','Scarfs',NULL,0,1,2,20,0);
INSERT INTO "apparel_category" VALUES(29,'racing','Racing',NULL,0,1,2,19,0);
INSERT INTO "apparel_category" VALUES(30,'hoodie','Hoodie',NULL,0,1,2,11,0);
INSERT INTO "apparel_category" VALUES(31,'pullover','Pullover',NULL,0,1,2,18,0);
COMMIT;
