# Ubuntu upstart file at /etc/init/redis.conf

pre-start script
    mkdir -p /var/lib/redis/
    mkdir -p /var/log/redis/
end script

start on runlevel [2345]
stop on runlevel [06]

script
  ENABLE_REDIS="yes"
  if [ -f /etc/default/redis ]; then . /etc/default/redis; fi
  if [ "x$ENABLE_REDIS" = "xyes" ]; then exec start-stop-daemon --start --quiet --chuid redis --exec  /usr/local/bin/redis-server -- /etc/redis.conf; fi
end script
